feat: add tournaments
thelastandrew/frontendiya-tech pull request #15
Opened 2023-05-05 22:05 UTC by ViktorMank

2023-05-06 06:05 UTC, remadyt requested changes

2023-05-06 06:05 UTC, remadyt commented on src/components/tournaments/Modal/TournamentsModal.tsx
> +          data={ModalSelectorsData.FORMATS}
incorrect constant name. renamte to TOURNOMENTS_CONFIG

2023-05-06 06:05 UTC, remadyt commented on src/components/tournaments/Modal/TournamentsModal.tsx
> +          <Button type="submit">{t('modals.createTournament')}</Button>
why u rename to modals?

2023-05-06 06:05 UTC, remadyt commented on src/constants/databasePaths.ts
> +  TOURNAMENTS = 'tournaments',
incorrect name, User, Tournaments for all enum use this style

2023-05-06 06:05 UTC, remadyt commented on src/helpers/emptyText.ts
> +  return text || t('tournaments.unknownInfo');
need to get rid of this feature

2023-05-06 06:05 UTC, remadyt commented on src/pages/TournamentInfo/TournamentInfo.tsx
> +  const tournamentData = useMemo(() => {
need getById request

2023-05-06 06:05 UTC, remadyt commented on src/store/slices/tournaments/tournamentsSlice.ts
> +      notifications.show({
use common funcation for this

2023-05-06 06:05 UTC, remadyt commented on src/store/slices/tournaments/tournamentsSlice.ts
> +        isFetching: false,
check Andrey slices, now not needed make object copy

2023-05-06 12:51 UTC, suveiko commented on src/components/tournaments/Modal/config.ts
> +export const ModalSelectorsData = {
Can we create a type for this object?

2023-05-06 19:38 UTC, thelastandrew requested changes

2023-05-06 19:38 UTC, thelastandrew commented on src/store/slices/tournaments/tournamentsSlice.ts
> +    set((state) => ({
you can now do the same this way useing `immer`:
```
import { produce } from 'immer';

/// you code

set(produce(state: TournamentsStore) => { state.isFetching = true; });
```

2023-05-22 07:03 UTC, remadyt approved these changes

2023-05-22 08:15 UTC, thelastandrew approved these changes

2023-05-22 08:17 UTC, merged