Feat/phone auth
thelastandrew/frontendiya-tech pull request #2
Opened 2023-04-21 21:07 UTC by thelastandrew

Features implemented:
- phone auth

Features removed:
- email/pass registration
- email/pass auth
- reset pass

2023-04-22 07:52 UTC, remadyt requested changes

2023-04-22 07:52 UTC, remadyt commented on src/App.tsx
> +  const { getAuth, isFetching } = useStore((state) => state);
incorrect hook name, rename to useAuth

2023-04-22 07:52 UTC, remadyt commented on src/App.tsx
>    if (isFetching) return <LoaderScreen />;
create container component for loader

2023-04-22 07:52 UTC, remadyt commented on src/components/Header/Header.tsx
> +              <Button onClick={closeDrawer} component={Link} to={Paths.signin}>
handleCloseDrawer

2023-04-22 07:52 UTC, remadyt commented on src/components/Header/Header.tsx
> +                <Button onClick={signOut.signOut}>
move to function and use destructuring, it is used in at least 2 places

2023-04-22 07:52 UTC, remadyt commented on src/components/SignInForm/SignInForm.tsx
> +  const [showOTPInput, setShowOTPInput] = useState<boolean>(false);
use 'is' prefix for boolean

2023-04-22 07:52 UTC, remadyt commented on src/components/SignInForm/SignInForm.tsx
> +export const SignInForm: FC<PaperProps> = (props) => {
use destructuring for props

2023-04-22 07:52 UTC, remadyt commented on src/components/SignInForm/SignInForm.tsx
> +  const OPTForm = useForm({
why u use 2 forms?

2023-04-22 07:52 UTC, remadyt commented on src/components/SignInForm/SignInForm.tsx
> +          {signIn.isFetching && <LoaderScreen />}
use desctructuring

2023-04-22 07:52 UTC, remadyt commented on src/components/SignInForm/SignInForm.tsx
> +      successNotification(title, message);
do not use if else
```
    let title = t('notifications.error-header');
    let message = t('notifications.verification-error');
if(error) {
      errorNotification(title, message);
      
      return;
}

      title = t('notifications.error-header');
      message = t('notifications.verification-error');

      errorNotification(title, message);

2023-04-22 07:52 UTC, remadyt commented on src/components/SignInForm/SignInForm.tsx
> +          {getOTP.isFetching && <LoaderScreen />}
use container here

2023-04-22 07:52 UTC, remadyt commented on src/integrations/firebase/phoneAuth.ts
> +  (window as FBWindow).recaptchaVerifier = new RecaptchaVerifier(
need move this to const
```
const extendedWindow = (window as FBWindow);
and reuse in all palces
```

2023-04-22 07:52 UTC, remadyt commented on src/integrations/firebase/phoneAuth.ts
> +  const result = await (window as FBWindow).confirmationResult.confirm(code);
const { user }

2023-04-22 07:52 UTC, remadyt commented on src/integrations/firebase/phoneAuth.ts
> +export const appSignOut = async (): Promise<void> => {
incorrect name

2023-04-22 07:52 UTC, remadyt commented on src/store/slices/initSlice/initSlice.ts
> +  phone: Nullable<string>;
nullable is redundant here

2023-04-22 07:52 UTC, remadyt commented on src/store/slices/initSlice/initSlice.ts
> +export type InitSlice = {
incorrect name, IState

2023-04-22 22:26 UTC, thelastandrew commented on src/App.tsx
> +  const { getAuth, isFetching } = useStore((state) => state);
this in not a hook, it's a store 'action'

2023-04-24 20:53 UTC, thelastandrew commented on src/integrations/firebase/phoneAuth.ts
> +export const appSignOut = async (): Promise<void> => {
if rename to signOut, then it has conflict with the built-in firebase method

2023-04-25 10:07 UTC, merged