feat: add team
thelastandrew/frontendiya-tech pull request #31
Opened 2023-06-11 23:56 UTC by ViktorMank

2023-06-12 08:18 UTC, remadyt requested changes

2023-06-12 08:18 UTC, remadyt commented on src/components/Team/TeamInfoPanel/TeamInfoPanel.tsx
> +    return members.map((member) => <TeamUserItem key={member.id} member={member} />);
why need return here? use ()

2023-06-12 08:18 UTC, remadyt commented on src/components/Team/TeamUserItem/TeamUserItem.tsx
> +        theme.colorScheme === 'dark' ? theme.colors.dark[8] : theme.colors.gray[0],
take it out as a global constant IS_DARK_THEME

2023-06-12 08:18 UTC, remadyt commented on src/components/Team/TeamUserItem/TeamUserItem.tsx
> +export const TeamUserItem: FC<{ member: IUser }> = ({
type Props

2023-06-12 08:18 UTC, remadyt commented on src/components/Team/TeamUserItem/TeamUserItem.tsx
> +        {role === Roles.CAPTAIN && <IconCrown color="orange" size={25} />}
use role from hook

2023-06-12 08:18 UTC, remadyt commented on src/components/profile/ProfileCreateTeamModal/ProfileCreateTeamModal.tsx
> +      tag: (value) => (value ? null : t('modals.requiredField')),
create common function for required field, and use on all such places

2023-06-12 08:18 UTC, remadyt commented on src/components/profile/ProfileCreateTeamModal/ProfileCreateTeamModal.tsx
> +    await getTeams();
why need await ? remove

2023-06-12 08:18 UTC, remadyt commented on src/components/profile/ProfileUpdateUserModal/ProfileUpdateUserModal.tsx
> +      name: (value) => (value ? null : 'Введите имя'),
add translate

2023-06-12 08:18 UTC, remadyt commented on src/components/profile/ProfileUpdateUserModal/ProfileUpdateUserModal.tsx
> +    await updateUserDataField({ name: form.values.name });
remove await

2023-06-12 08:18 UTC, remadyt commented on src/components/tournaments/Modal/TournamentsModal.tsx
> +          data={GAMES}
rename this const, need more info

2023-06-12 08:18 UTC, remadyt commented on src/helpers/uniqueIdGenerator.ts
> +  return uniqid(`${path}-`);
remove return

2023-06-12 08:18 UTC, remadyt commented on src/integrations/firebase/database.ts
> +export const getFirestoreTeamsLength = async (
create common function for this

2023-06-12 08:18 UTC, remadyt commented on src/pages/Profile/Profile.tsx
> +    return teams.map((team) => <TeamLink key={team.id} teamData={team} />);
remove return

2023-06-12 08:18 UTC, remadyt commented on src/pages/Profile/Profile.tsx
> +  const getTeamsItems = (): any => {
fix any

2023-06-12 08:18 UTC, remadyt commented on src/pages/Profile/Profile.tsx
> +            {teams.length ? getTeamsItems() : null}
use &&

2023-06-12 08:18 UTC, remadyt commented on src/pages/Profile/Profile.tsx
> +              Друзья
add translate

2023-06-12 08:18 UTC, remadyt commented on src/pages/Profile/Profile.tsx
> +              Статистика
add translate

2023-06-12 08:18 UTC, remadyt commented on src/pages/TeamInfo/TeamInfo.tsx
> +            theme.colorScheme === 'dark' ? '#1A1B1E' : theme.white
use global const

2023-06-12 08:18 UTC, remadyt commented on src/store/slices/teams/teamsSlice.ts
> +  updateTeam: (data: any) => any;
fix any

2023-06-12 08:18 UTC, remadyt commented on src/store/slices/teams/teamsSlice.ts
> +      if (teamsCount >= 5) {
const

2023-06-12 08:18 UTC, remadyt commented on src/store/slices/teams/teamsSlice.ts
> +    const currentUser = get().user as IUser;
is it possible to declare it at the top 1 time?

2023-06-13 10:12 UTC, ViktorMank commented on src/components/profile/ProfileCreateTeamModal/ProfileCreateTeamModal.tsx
> +    await getTeams();
because this is an asynchronous function, first we add data to the database and only then we make a request to receive it

2023-06-13 10:35 UTC, ViktorMank commented on src/pages/Profile/Profile.tsx
> +            {teams.length ? getTeamsItems() : null}
in this variant, if the length of the command array = 0,
![Screenshot_2](https://github.com/thelastandrew/frontendiya-tech/assets/95700178/0f0646e1-1b2f-4ca9-ac5b-8a247ca9bb61)

2023-06-13 11:18 UTC, remadyt approved these changes

2023-06-13 11:36 UTC, merged