feat: add firestore database
thelastandrew/frontendiya-tech pull request #4
Opened 2023-04-25 15:58 UTC by ViktorMank

2023-04-26 19:06 UTC, thelastandrew commented on src/store/slices/initSlice/initSlice.ts
> +import { getUserData } from '../../../integrations/firebase/usersDatabase';
fix path 'integrations/firebase/usersDatabase'

2023-04-26 19:07 UTC, thelastandrew commented on src/store/slices/signInSlice/signInSlice.ts
> +import { getUserData, setUserData } from '../../../integrations/firebase/usersDatabase';
fix path 'integrations/firebase/usersDatabase'

2023-04-26 19:13 UTC, thelastandrew commented on src/store/slices/signInSlice/signInSlice.ts
> +            console.error(error);
delete console.log, set error to the corresponding property of the slice (see line 10)

2023-04-26 19:14 UTC, thelastandrew commented on src/store/slices/initSlice/initSlice.ts
> +  role: string;
role: 'user' | 'admin'

2023-04-26 19:25 UTC, thelastandrew commented on src/store/slices/signInSlice/signInSlice.ts
> +                role: 'user',
role: user.role | 'user'

2023-04-26 19:27 UTC, thelastandrew commented on src/store/slices/signInSlice/signInSlice.ts
> -            user: {
we still need to set current user to the store

2023-04-26 19:30 UTC, thelastandrew commented on src/store/slices/signInSlice/signInSlice.ts
> -              isFetching: false,
and to set fetching to false

2023-04-26 19:33 UTC, thelastandrew commented on src/store/slices/initSlice/initSlice.ts
> +          console.error(error);
remove console.log,
declare nullable property 'error',
set caught error to this property,
then we can handle this 'error' in React component

2023-04-26 19:38 UTC, thelastandrew requested changes
.

2023-04-27 09:29 UTC, remadyt requested changes

2023-04-27 09:29 UTC, remadyt commented on src/store/slices/initSlice/initSlice.ts
> +  role: string;
create enum for this

2023-04-27 09:29 UTC, remadyt commented on src/store/slices/initSlice/initSlice.ts
> +          console.error(error);
maybe use notification here? and all such places

2023-04-27 09:29 UTC, remadyt commented on src/store/slices/signInSlice/signInSlice.ts
> +                role: 'user',
dont handle role from frontend. need set roles only in db

and why u desctruring this object? setUserData(user) not working?

2023-04-28 13:15 UTC, remadyt requested changes

2023-04-28 13:15 UTC, remadyt commented on src/components/shared/ProtectedRoute/ProtectedRoute.tsx
> +  return children as ReactElement;
```
const ProtectedRoute = ({ children, isPrivate = true, allowedRoles }: ProtectedRouteProps) => {
  const { isAuth, user } = useAuth((state) => state);
  const userHasRequiredRole = user?.role !== undefined && allowedRoles.includes(user.role);

  if (!isAuth && isPrivate) {
    return <Navigate to={Paths.home} replace />;
 };
  if (isAuth && isPrivate && !userHasRequiredRole) {
    return <Navigate to={Paths.home} replace />;
};

  return children;
};
```
i think its same?

2023-04-28 17:56 UTC, thelastandrew approved these changes

2023-04-29 07:40 UTC, remadyt approved these changes

2023-04-29 07:40 UTC, merged