feat: add user-profle
thelastandrew/frontendiya-tech pull request #9
Opened 2023-04-30 22:47 UTC by thelastandrew

2023-05-01 07:37 UTC, remadyt requested changes

2023-05-01 07:37 UTC, remadyt commented on package.json
> +    "@mantine/dropzone": "^6.0.9",
implement upload image without dropzone, picture should change to onChange

2023-05-01 07:37 UTC, remadyt commented on src/components/Field/Field.tsx
> +export const Field: FC<Props> = ({ fieldName, value }) => {
1) incorrect name, it's too generic. maybe EditableField
2) move to component/shared
3) implement this without ``` const [inputValue, setInputValue] = useInputState<string>(value);``` input must be controlled via form

2023-05-01 07:37 UTC, remadyt commented on src/components/Field/Field.tsx
> +        style={{ opacity: hovered ? 1 : 0 }}
1) make it always visible
2) fix jumping layout after switch to Text Input

2023-05-01 07:37 UTC, remadyt commented on src/pages/Profile/Profile.tsx
> +          accept={['image/png', 'image/jpeg', 'image/jpg']}
create constant with IMAGE_FORMATS and ALLOWED_IMAGE_FORMATS and past here

2023-05-01 07:37 UTC, remadyt commented on src/pages/Profile/Profile.tsx
> +          style={{ border: 'none' }}
do not use style, use only className

2023-05-01 07:37 UTC, remadyt commented on src/pages/Profile/Profile.tsx
> +            style={{ cursor: 'pointer' }}
do not use style, use only className

2023-05-01 07:37 UTC, remadyt commented on src/pages/Profile/Profile.tsx
> +          <Container px={0}>{(user as IUser).phone}</Container>
(user as IUser).phone  try to use destructuring, if it doesn't work put it in a constant ```(user as IUser)``` **in all similar places**

2023-05-01 07:37 UTC, remadyt commented on src/store/slices/signInSlice/signInSlice.ts
> +          } finally {
finally must come after catch

2023-05-01 07:37 UTC, remadyt commented on src/store/slices/signOutSlice/signOutSlice.ts
> +      await appSignOut();
why u remove try catch here?

2023-05-01 07:37 UTC, remadyt commented on src/store/slices/updateUserSlice/updateUserSlice.ts
> +    updateUserDataField: (user: IUser, fieldToUpdate: IDataField, t: TF) => Promise<void>;
incorrect name

2023-05-01 07:37 UTC, remadyt commented on src/store/slices/updateUserSlice/updateUserSlice.ts
> +  updateUser: {
are you sure you need to invest here?

2023-05-01 07:37 UTC, remadyt commented on src/store/slices/updateUserSlice/updateUserSlice.ts
> +import { GenericStateCreator } from 'store/types';
fix imports, they can be combined

2023-05-01 07:37 UTC, remadyt commented on src/store/store.ts
> +  ...updateUserSlice(...a),
this does not apply to useAuth

2023-05-01 07:37 UTC, remadyt commented on src/store/slices/updateUserSlice/updateUserSlice.ts
> +            ...fieldToUpdate,
https://immerjs.github.io/immer/ check this tool for zustand, i think need implement this for all slices

2023-05-01 07:37 UTC, remadyt commented on src/store/slices/updateUserSlice/updateUserSlice.ts
> +        notifications.show({
create common function for this notification

2023-05-01 16:40 UTC, ViktorMank commented on src/components/HeaderUserMenu/HeaderUserMenu.tsx
> +        <Menu.Label>Account</Menu.Label>
can show the username instead account

2023-05-01 16:46 UTC, ViktorMank commented on src/integrations/firebase/usersDatabase.ts
> +  const db = getDatabase();
why we can't import it from firebase.ts

2023-05-03 23:08 UTC, thelastandrew commented on src/store/store.ts
> +  ...updateUserSlice(...a),
as long as updateUserSlice manipulates user property of this store, it cannot be separated

2023-05-04 07:48 UTC, remadyt commented on src/components/profile/ProfileImageUploader/ProfileImageUploader.tsx
> +const ALLOWED_IMAGE_FORMATS = ['image/png', 'image/jpg', 'image/jpeg'];
move to global constants

2023-05-04 07:49 UTC, remadyt commented on src/components/profile/ProfileImageUploader/ProfileImageUploader.tsx
> +        onChange={(file) => setImage(file)}
call handleUpload instead of setImage

2023-05-04 07:50 UTC, remadyt commented on src/components/profile/ProfilePersonalDataForm/ProfilePersonalDataForm.tsx
> +type PropsType = {
rename to Props

2023-05-04 07:51 UTC, remadyt commented on src/components/shared/Form/FormComponent/FormComponent.tsx
> +  return <div className={classes.form}>{children}</div>;
i think this component not needed

2023-05-04 07:51 UTC, remadyt commented on src/helpers/notifications/notifications.ts
> +import { notifications } from '@mantine/notifications';
helper folder is not needed

2023-05-04 07:52 UTC, remadyt commented on src/integrations/firebase/storage.ts
> +  return getDownloadURL(imageRef);
are you sure you don't need error handling?

2023-05-04 07:53 UTC, remadyt commented on src/integrations/i18n/resources/en.ts
> +      'upload-image': 'Upload image',
use camelCase

2023-05-04 07:53 UTC, remadyt commented on src/integrations/i18n/resources/ru.ts
> +      'upload-image': 'Загрузить картинку',
use camelCase

2023-05-04 07:54 UTC, remadyt commented on src/pages/Profile/Profile.tsx
> +      <ProfilePersonalDataForm user={user as IUser} />
as user looks weird

2023-05-04 07:58 UTC, remadyt commented on src/components/profile/ProfileImageUploader/ProfileImageUploader.tsx
> +    <Container ta="center" m={0} pos="relative">
need add cursor pointer, and upload icon
<img width="144" alt="image" src="https://user-images.githubusercontent.com/74316916/236144448-9250fbad-1a43-4c03-ab15-c39fcabe2c47.png">

2023-05-04 08:02 UTC, remadyt commented on src/components/profile/ProfilePersonalDataForm/ProfilePersonalDataForm.tsx
> +          <LoadingOverlay visible={isUpdatingUserData} />
here use loader on Button

2023-05-04 08:17 UTC, remadyt commented on src/store/slices/updateUserSlice/updateUserSlice.ts
> +  isUpdatingUserData: boolean;
rename to isUpdateUserInfoFetching

2023-05-04 08:21 UTC, remadyt requested changes

2023-05-04 08:23 UTC, remadyt commented on src/components/layout/Header/Header.tsx
> +    signOut.signOut(t);
use destructuring here

2023-05-04 08:24 UTC, remadyt commented on src/components/profile/ProfileImageUploader/ProfileImageUploader.tsx
> +  const [image, setImage] = useState<Nullable<File>>(null);
implement  image uploading without useState

2023-05-04 08:25 UTC, remadyt commented on src/store/slices/updateUserSlice/updateUserSlice.ts
> +  updateUserDataField: (user: IUser, fieldToUpdate: IDataField, t: TF) => Promise<void>;
rename to updateUserInfo

2023-05-04 13:20 UTC, remadyt approved these changes

2023-05-04 14:03 UTC, merged